services:
  db:
    image: postgres:16
    container_name: palm_db
    restart: always
    # --- PRODUCTION (Linux) ---
    # network_mode: "host"
    # --- LOCAL MAC ---
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: palm_api
    restart: always
    # --- PRODUCTION (Linux) ---
    # network_mode: "host"
    # --- LOCAL MAC ---
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      # --- PRODUCTION (Linux) ---
      # - DB_HOST=localhost
      # --- LOCAL MAC ---
      - DB_HOST=db
      - DB_PORT=5432
      - APP_PORT=${APP_PORT:-8080}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: